# Generated by Django 5.2.1 on 2025-07-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.title')),
            ],
            options={
                'unique_together': {('post', 'title')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='posts', through='news.PostTitle', to='news.title'),
        ),
    ]
